name: comparem2-ci
channels:
  - conda-forge
  - bioconda
dependencies:
  - snakemake-minimal <8
  - pulp <2.8
  - python <3.12
  - mamba <2 # Necessary for snakemake to install child environments during development.
  - pandas
  
  
# mamba env create -f environment.yaml

# This file must match the meta.yaml on bioconda
