name: comparem2-ci
channels:
  - conda-forge
  - bioconda
dependencies:
  - mamba # probably is on the system already.
  - snakemake=7.32.4 # Last version before they completely changed the structure.
  
  
# mamba env create -f environment.yaml

